baseURL: "http://blog.poulpix.fr/"
languageCode: en-us
title: Poulpix's Blog
theme: hugo-PaperMod

googleAnalytics: G-9P0BJNQQ6S

params:
  homeInfoParams:
    Title: "Welcome to my web home !"
    Content: |
      Tech / DevOps / SRE Blog
      
  socialIcons:
    - name: "twitter"
      url: "https://twitter.com/Poulpix"
    - name: "linkedin"
      url: "https://www.linkedin.com/in/valentin-scotte-832b3a65/"
